|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|drivers/input/tablet/Makefile|drivers/input/tablet/Makefile|not calculated|0|not calculated|not calculated|0|3
