|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Kbuild|MODIFY|arch/s390/Kbuild|arch/s390/Kbuild|not calculated|0|not calculated|not calculated|0|1
