|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|drivers/media/platform/verisilicon/Makefile|drivers/media/platform/verisilicon/Makefile|not calculated|0|not calculated|not calculated|1|0
