|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Kbuild|DELETE|arch/ia64/include/uapi/asm/Kbuild||not calculated|0|not calculated|not calculated|0|2
