|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|arch/s390/lib/Makefile|arch/s390/lib/Makefile|not calculated|0|not calculated|not calculated|1|1
