|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|drivers/net/ethernet/mellanox/mlxsw/Makefile|drivers/net/ethernet/mellanox/mlxsw/Makefile|not calculated|0|not calculated|not calculated|5|4
