|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|ADD|new file|drivers/net/wireless/rtlwifi/rtl8821ae/Makefile|not calculated|0|not calculated|not calculated|19|0
