|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|ADD|new file|drivers/staging/media/atomisp/platform/intel-mid/Makefile|not calculated|0|not calculated|not calculated|5|0
