|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|ADD|new file|drivers/net/ethernet/mellanox/mlx5/core/esw/Makefile|not calculated|0|not calculated|not calculated|2|0
