|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|RENAME|drivers/video/via/Makefile|drivers/video/fbdev/via/Makefile|not calculated|0|not calculated|not calculated|0|0
