|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|RENAME|drivers/net/wireless/ti/wl12xx/Makefile|drivers/net/wireless/ti/wlcore/Makefile|not calculated|0|not calculated|not calculated|0|0
