|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|sound/soc/codecs/Makefile|sound/soc/codecs/Makefile|not calculated|0|not calculated|not calculated|2|0
