|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|RENAME|drivers/net/wireless/brcm80211/brcmutil/Makefile|drivers/net/wireless/broadcom/brcm80211/brcmutil/Makefile|not calculated|0|not calculated|not calculated|2|2
