|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Kbuild|MODIFY|drivers/scsi/cxgbi/cxgb4i/Kbuild|drivers/scsi/cxgbi/cxgb4i/Kbuild|not calculated|0|not calculated|not calculated|1|1
