|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|ADD|new file|drivers/scsi/mpt3sas/Makefile|not calculated|0|not calculated|not calculated|8|0
