|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|drivers/gpu/drm/amd/display/dc/link/Makefile|drivers/gpu/drm/amd/display/dc/link/Makefile|not calculated|0|not calculated|not calculated|2|1
