|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|arch/x86/kvm/Makefile|arch/x86/kvm/Makefile|not calculated|0|not calculated|not calculated|2|1
