|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|drivers/gpu/drm/amd/display/dc/dcn32/Makefile|drivers/gpu/drm/amd/display/dc/dcn32/Makefile|not calculated|0|not calculated|not calculated|9|5
