|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|fs/btrfs/Makefile|fs/btrfs/Makefile|not calculated|0|not calculated|not calculated|15|35
