|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|fs/ocfs2/Makefile|fs/ocfs2/Makefile|not calculated|0|not calculated|not calculated|4|0
