|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|RENAME|drivers/net/wireless/rtlwifi/rtl8821ae/Makefile|drivers/net/wireless/realtek/rtlwifi/rtl8821ae/Makefile|not calculated|0|not calculated|not calculated|0|0
