|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Kbuild|MODIFY|include/asm-s390/Kbuild|include/asm-s390/Kbuild|not calculated|0|not calculated|not calculated|1|0
