|File Name|Change Type|Local File PATH Old|Local File PATH New|Complexity|Methods|Tokens|Lines Of Code (nloc)|Lines Added|Lines Deleted
0|Makefile|MODIFY|drivers/dma-buf/Makefile|drivers/dma-buf/Makefile|not calculated|0|not calculated|not calculated|1|1
